### ISSUE TITLE
Internal Error on Azure Table when deploying a linker through IaC

### ISSUE THREAD

**Issue by rhuanbarreto** [Azure/ServiceConnector#9]
I got this when using Pulumi for deploying a linker:

```
* Status=200 Code="TaskSystemGeneralError" Message="Write task internal data failed.. Update entity failed with error: The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.
    RequestId:94a6d2b4-1002-0029-025b-d5c98e000000
    Time:2025-06-04T14:21:01.9552912Z
    Status: 400 (Bad Request)
    ErrorCode: PropertyValueTooLarge
    
    Content:
    {"odata.error":{"code":"PropertyValueTooLarge","message":{"lang":"en-US","value":"The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.\nRequestId:94a6d2b4-1002-0029-025b-d5c98e000000\nTime:2025-06-04T14:21:01.9552912Z"}}}
    
    Headers:
    Cache-Control: no-cache
    Transfer-Encoding: chunked
    Server: Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0
    x-ms-request-id: 94a6d2b4-1002-0029-025b-d5c98e000000
    x-ms-client-request-id: 898b8f71-6fe4-4c8b-bd64-ea1ed6419ea2
    x-ms-version: REDACTED
    X-Content-Type-Options: REDACTED
    Date: Wed, 04 Jun 2025 14:21:01 GMT
    Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8
    , PropertyValueTooLarge, "
```
